minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade

shellEmulator: true

packages:
  - playground

overrides:
  errx: 'workspace:*'

allowBuilds:
  esbuild: false
  simple-git-hooks: true
